### PR TITLE
test flyci

### PR DESCRIPTION
**Pull request by jdeniau**

### CODE REVIEW

**Comment by kgantchev** [comment]
Hi @jdeniau,

I'm the CEO and co-founder of [FlyCI](https://www.flyci.net/?utm_source=github&utm_medium=community&utm_campaign=comment), thank you for using our Mac runners! We would love to get your feedback and add it to [our case studies section](https://www.flyci.net/case-studies?utm_source=github&utm_medium=community&utm_campaign=recommend). It will highlight your project to our visitors and it will help us grow our community. Are you OK with sharing your feedback and getting your project highlighted in our case studies section?

**Comment by jdeniau** [comment]
Hi @kgantchev 

I tried flyci as I didn't found that `macos-14`github runner run's on arm.
In Flyci, I had a sign issue with electron packager, so I tried back github arm runner (found in between).
I has the same issue on my mac though, and in fact, it was related to the number of opened file on arm !

I resolved with https://github.com/jdeniau/tiana-tables/pull/59/files
and opened https://github.com/electron/forge/issues/3540 on the electron side to make debug easier.

I think I will kept the github runner for the following reason : 
- My package is quite a small application for now, and I do not have huge requirements,
- I build for both windows, linux and mac, so I prefer keeping all my CI in the same spot,
- I trust github more than I do trust flyci,
- Your application asks for "**Read** and **write** access to administration" : it may be required, but I feel unsafe giving you that access.

What I can grant your service though:
- Installation is super easy, I did not think that an external service could be that easy,
- the build seems to be really faster than github's (but I did not timed it, and it's your marketing, so my brain may have been tricked)

**Comment by jdeniau** [comment]
(closing this for the record as problem was solved in #59 )

**Comment by kgantchev** [comment]
Thanks for providing us with this insightful feedback! I appreciate you giving FlyCI a shot and I'll take your feedback to our team.

**Pull request closed without merging**
